name: Deploy Bot  # Nama proses

on: [push]  # Proses ini akan berjalan setiap kali ada push

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan proses di Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Mengambil semua kode dari repositori

      - name: Run Bot Code
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          node mybot.js  # Ganti "mybot.js" dengan nama file bot kamu
