name: Kirim Pesan ke Bot Telegram

on:
  push:
    branches:
      - main  # Workflow ini akan berjalan setiap kali ada push di branch "main"

jobs:
  send_telegram_message:
    runs-on: ubuntu-latest  # Sistem operasi yang akan digunakan GitHub Actions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Menggunakan Node.js versi 16

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Kirim Pesan ke Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node sendMessage.js  # Menjalankan file sendMessage.js untuk mengirim pesan
