name: Kirim Pesan ke Bot Telegram

on:
  push:
    branches:
      - main  # Ini artinya workflow akan berjalan setiap kali ada push di branch "main"

jobs:
  send_telegram_message:
    runs-on: ubuntu-latest  # Sistem operasi yang akan digunakan GitHub Actions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Kirim Pesan ke Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" \
          -d text="Kode kamu telah diperbarui di branch main."
